### ISSUE TITLE
Break-up Review section

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#10]
I see where you're reviewing Intro, but not Excel I. 

Here's some thoughts:
+ Keep this as a review of Intro
+ Remove reference to Excel I and review later when you get into the exercise
+ Be mindful you're introducing a new concept when you're trying to review. This is going to add additional friction. Usually I don't like to introduce new learning when I review. Maybe do this as a collaborative group activity you can guide easier to tease out key concepts from everyone and construct together rather than run a full protocol for it. At this point, I think we have every reason to get into the data as quickly as possible while still respecting the "softer" skills and mindsets we're trying to reinforce.
+ Please think about keeping your formatting more consistent. I'm not a fan of the abbreviation. The header "A Review of Intro. to Data Analytics and Excel for Data Analysis I" should really be its own slide, with the exercise on a second by itself.

**Comment by datapolitan** [comment]
@lizdumont Remember that the group ideation and your process mapping are reviews. I'd just do a quick brainstorm check-in with the concept map (maybe not even call it that or really get too deep into what it is) and then leverage the exercises with the data to remind them of key concepts, connecting it back to previous learning

**Comment by lizdumont** [comment]
The intention for the concept map was two-fold: to get them engaged in an activity so that day doesn't start with them working solo behind their computers, and to include concepts from both classes. So, ideation (Intro) would go on the process map as well as conditional formatting (Excel I).

I have no problem with pulling out the activity completely. I do want them engaged with each other right off the bat. Do you think the questioning ideation around the two data sets is sufficient?

**Comment by lizdumont** [comment]
@datapolitan The intention for the concept map was two-fold: to get them engaged in an activity so that day doesn't start with them working solo behind their computers, and to include concepts from both classes. So, ideation (Intro) would go on the process map as well as conditional formatting (Excel I).

I have no problem with pulling out the activity completely. I do want them engaged with each other right off the bat. Do you think the questioning ideation around the two data sets is sufficient?

**Comment by lizdumont** [comment]
Made some edits based off of our convo. Let me know what you think.

**Comment by datapolitan** [comment]
@lizdumont This looks good. Just make sure you provide the prompt for what their ideating around. You could even make it the title of the slide. 

Also, I think the 7 minutes is as a "class" vs a "group"

**Comment by datapolitan** [comment]
@lizdumont I'm still not sure what the question is you want them to ideate on for [the review](http://training.datapolitan.com/parks-excel-analysis-ii/#25). Mind adding an explicit question as the title for the slide? 

Some suggestions:
+ What do you remember from Intro?
+ What topics do you remember covering in Intro?
+ What do you remember most from Intro?
+ What's been the most impactful topic from Intro?

You can combine Excel I in this as well, but whatever you do, I'd make it explicit on the slide for visual learners, people who need to be reminded, and people not paying attention

**Comment by lizdumont** [comment]
Sure that makes sense. Will do.

**Comment by datapolitan** [comment]
Sorry @lizdumont. I don't think the question you had was quite clear enough as a brainstorming prompt. I think the question needs to reference the learning that has taken place specifically in our classes.
