### ISSUE TITLE
"Today's Data" clarification

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#11]
A few questions:
+ What do you want them to do with the data links on this slide?
+ Why are you introducing the concept of getting data via SQL Server at this point? Seems to be an overload of topics/ideas early on in the experience for items we can include later in the `References` section

**Comment by datapolitan** [comment]
@lizdumont To do the ideation and process mapping, they're going to need to look at the data. This could be your Excel I review, but make sure you have it guided. You can reuse the slides from Excel I for this. The key concept is the 5 basic tasks and how they do that with one of the datasets we introduce. Remember in Excel Tools, we introduce the second dataset later. There's no reason to over-saturate them with datasets, especially given how problematic these datasets are to work with for learners

**Comment by lizdumont** [comment]
This slide is where they download the data, via the links, and we do a data walk of both together. It comes immediately before the ideation and process mapping.

 I get what you're saying about introducing one dataset at a time, but to create the table, which is the first task of B block, they need to create a short borough and full borough column in both of the datasets in order to pull the number of inspections (PIP data) and number of hours worked (daily tasks).

The first activity, the table, pulls an aggregation from both datasets together without doing a VLOOKUP. The second half of this block is answering a question that requires a VLOOKUP.

**Comment by lizdumont** [comment]
@datapolitan This slide is where they download the data, via the links, and we do a data walk of both together. It comes immediately before the ideation and process mapping.

I get what you're saying about introducing one dataset at a time, but to create the table, which is the first task of B block, they need to create a short borough and full borough column in both of the datasets in order to pull the number of inspections (PIP data) and number of hours worked (daily tasks).

The first activity, the table, pulls an aggregation from both datasets together without doing a VLOOKUP. The second half of this block is answering a question that requires a VLOOKUP.

**Comment by lizdumont** [comment]
I moved the SQL preview to the end and will datawalk only one dataset. Will wait to see if it's supervisor inspection data or daily tasks.

**Comment by datapolitan** [comment]
@lizdumont Sounds good. The data should be in the `data` folder and linked directly there.
